version: '3.4'

services:
  db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
  mssqlscripts:
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S db -U sa -P "S3cur3P@ssW0rd!" -Q "create database Keycloak"; do sleep 5; done'
  intive.patronage2023.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/intivepatronageapi.pfx
    ports:
      - "5080:80"
      - "5081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${USERPROFILE}/.aspnet/https:/https/
  keycloak:
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/root/data/import/realm-config.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin1
      - KEYCLOAK_ADMIN_PASSWORD=admin1
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql
      - DB_ADDR=db
      - DB_PORT=1433
      - DB_DATABASE=keycloak
      - DB_USER=sa
      - DB_PASSWORD=S3cur3P@ssW0rd!
      - JAVA_OPTS=-Xms512m -Xmx2048m
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./realm-config.json:/root/data/import/realm-config.json
    restart: always
  smtp4dev:
    ports:
      - '3000:80' # WebInterface
      - '25:25' # SMTP server
      - '143:143' # IMAP server
    environment:
      - ServerOptions__HostName=smtp4dev
  azurite:
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"